### ISSUE TITLE
Add Generic (Record r) r' instance using RowToList

### ISSUE THREAD

**Issue by rightfold** [purescript/purescript-generics-rep#12]

**Comment by paf31** [comment]
Actually, I'd like to remove record support, and have libraries use `RowToList` instead.

**Comment by rightfold** [comment]
That would be great

**Comment by rightfold** [comment]
Oh wait, you mean remove records from purescript-generics-rep, not PureScript?

**Comment by garyb** [comment]
Closing as record support is gone in 0.12 now.
