### ISSUE TITLE
link to Generics documentation in README

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-generics-rep#22]
https://github.com/purescript/documentation/blob/master/guides/Generic.md

If this makes sense, I'll make a PR when I have a moment.

**Comment by joncfoo** [comment]
👍 this is a good idea.

Ideally each package ought to be self-documented so as to not fall out-of-sync with docs elsewhere.  What are the thoughts around providing examples in the readme?

**Comment by hdgarrood** [comment]
I'd actually rather move those docs here; see https://github.com/purescript/documentation/issues/96

**Comment by hdgarrood** [comment]
Resolved by #31
